#!/usr/bin/env python3
"""Script to translate B2-learning-in-nn.ipynb from Norwegian to English"""

import json
import re

# Read the notebook
with open('B2-learning-in-nn.ipynb', 'r', encoding='utf-8') as f:
    notebook = json.load(f)

# Translation dictionary for common Norwegian words/phrases
translations = {
    # Cell 0 - Headers and intro
    "Prioritet: 1 (kjerne)": "Priority: 1 (core)",
    "# 🎓 B2: Læring i Nevrale Nettverk": "# 🎓 B2: Learning in Neural Networks",
    "**Fra Biologi til Kunstig Intelligens: Hvordan Nevrale Nettverk Lærer**": "**From Biology to Artificial Intelligence: How Neural Networks Learn**",
    "## 🎯 Mål for denne delen": "## 🎯 Goals for this Section",
    "I denne notebooken skal vi:": "In this notebook we will:",
    "- **Forstå** hvordan læring skjer i biologiske nevrale nettverk": "- **Understand** how learning occurs in biological neural networks",
    "- **Sammenligne** biologisk og kunstig læring": "- **Compare** biological and artificial learning",
    "- **Utforske** backpropagation og gradient descent": "- **Explore** backpropagation and gradient descent",
    "- **Implementere** trening, validering og testing": "- **Implement** training, validation, and testing",
    "- **Se** på overtilpasning og generalisering": "- **Examine** overfitting and generalization",
    "- **Bruke** PyTorch for praktiske eksempler": "- **Use** PyTorch for practical examples",
    
    # Section 1 - Biological foundations
    "## 🧠 1. Biologisk Fundament: Hvordan Lærer Hjernen?": "## 🧠 1. Biological Foundation: How Does the Brain Learn?",
    "Før vi utforsker kunstige nevrale nettverk, er det viktig å forstå hvordan læring skjer i biologiske nevrale nettverk - hjernen vår.": "Before we explore artificial neural networks, it is important to understand how learning occurs in biological neural networks - our brain.",
    "### Nevroplastisitet: Hjernens Læringsmekanisme": "### Neuroplasticity: The Brain's Learning Mechanism",
    "**Nevroplastisitet** er hjernens evne til å endre seg gjennom hele livet. Dette er grunnlaget for all læring og minne.": "**Neuroplasticity** is the brain's ability to change throughout life. This is the foundation for all learning and memory.",
    "#### Typer Nevroplastisitet": "#### Types of Neuroplasticity",
    "1. **Synaptisk Plastisitet**": "1. **Synaptic Plasticity**",
    "   - Endring i styrken på synapser mellom nevroner": "   - Changes in the strength of synapses between neurons",
    "   - **LTP (Long-Term Potentiation)**: Synapser blir sterkere ved gjentatt stimulering": "   - **LTP (Long-Term Potentiation)**: Synapses become stronger with repeated stimulation",
    "   - **LTD (Long-Term Depression)**: Synapser blir svakere ved mangel på stimulering": "   - **LTD (Long-Term Depression)**: Synapses become weaker with lack of stimulation",
    "2. **Strukturell Plastisitet**": "2. **Structural Plasticity**",
    "   - Dannelse av nye synapser (synaptogenese)": "   - Formation of new synapses (synaptogenesis)",
    "   - Vekst av nye dendritter og aksoner": "   - Growth of new dendrites and axons",
    "   - Dannelse av nye nevroner (neurogenese) i visse områder": "   - Formation of new neurons (neurogenesis) in certain areas",
    "3. **Funksjonell Plastisitet**": "3. **Functional Plasticity**",
    "   - Endring i hvordan nevroner responderer på stimuli": "   - Changes in how neurons respond to stimuli",
    "   - Reorganisering av nevrale kretser": "   - Reorganization of neural circuits",
    '### Hebb\'s Regel: "Nevroner som fyrer sammen, kobles sammen"': '### Hebb\'s Rule: "Neurons that fire together, wire together"',
    "**Donald Hebb (1949)** formulerte grunnprinsippet for nevroplastisitet:": "**Donald Hebb (1949)** formulated the fundamental principle of neuroplasticity:",
    "**Praktisk betydning**: Synapser blir sterkere når pre- og postsynaptiske nevroner aktiveres samtidig.": "**Practical significance**: Synapses become stronger when pre- and postsynaptic neurons are activated simultaneously.",
    "### Molekylære Mekanismer for Læring": "### Molecular Mechanisms for Learning",
    "#### 1. **NMDA-reseptorer og Calcium**": "#### 1. **NMDA Receptors and Calcium**",
    "- NMDA-reseptorer aktiveres ved samtidig glutamat-binding og depolarisering": "- NMDA receptors are activated by simultaneous glutamate binding and depolarization",
    "- Calcium-ioner strømmer inn og aktiverer signalveier": "- Calcium ions flow in and activate signaling pathways",
    "- Dette fører til LTP og synaptisk forsterkning": "- This leads to LTP and synaptic strengthening",
    "#### 2. **Protein Syntese**": "#### 2. **Protein Synthesis**",
    "- Calcium aktiverer cAMP-response element binding protein (CREB)": "- Calcium activates cAMP-response element binding protein (CREB)",
    "- CREB regulerer genuttrykk for proteiner viktige for synaptisk funksjon": "- CREB regulates gene expression for proteins important for synaptic function",
    "- Nye proteiner endrer synapsens struktur og funksjon": "- New proteins change the synapse's structure and function",
    "- Vekstfaktor som fremmer nevronal overlevelse og synaptogenese": "- Growth factor that promotes neuronal survival and synaptogenesis",
    "- Økt uttrykk ved læring og trening": "- Increased expression during learning and training",
    "- Viktig for langtidsminne og nevroplastisitet": "- Important for long-term memory and neuroplasticity",
    "### Læring på Systemnivå": "### Learning at the System Level",
    "#### 1. **Korttidshukommelse**": "#### 1. **Short-term Memory**",
    "- Aktivering av nevrale kretser i hippocampus og prefrontalcortex": "- Activation of neural circuits in hippocampus and prefrontal cortex",
    "- Krever kontinuerlig aktivitet for å opprettholdes": "- Requires continuous activity to be maintained",
    "- Kapasitet: ~7±2 elementer (Miller's Magic Number)<br>": "- Capacity: ~7±2 items (Miller's Magic Number)<br>",
    "#### 2. **Langtidshukommelse**": "#### 2. **Long-term Memory**",
    "- Konsolidering gjennom protein syntese": "- Consolidation through protein synthesis",
    "- Reorganisering fra hippocampus til neocortex": "- Reorganization from hippocampus to neocortex",
    "- Kan vare livet ut": "- Can last a lifetime",
    "#### 3. **Prosedyrlæring**": "#### 3. **Procedural Learning**",
    "- Basalganglier og cerebellum": "- Basal ganglia and cerebellum",
    "- Automatisering av motoriske og kognitive ferdigheter": "- Automation of motor and cognitive skills",
    '- "Muscle memory" - automatiske responser': '- "Muscle memory" - automatic responses',
    "### Klinisk Relevans": "### Clinical Relevance",
    "#### **Rehabilitering etter hjerneskade**": "#### **Rehabilitation after Brain Injury**",
    "- Nevroplastisitet muliggjør kompensasjon og gjenoppretting av funksjon": "- Neuroplasticity enables compensation and recovery of function",
    "- Tidlig intervensjon er kritisk": "- Early intervention is critical",
    "- Repetitiv trening fremmer reorganisering": "- Repetitive training promotes reorganization",
    "#### **Alderdom og kognitiv svikt**": "#### **Aging and Cognitive Decline**",
    "- Nevroplastisitet reduseres med alder": "- Neuroplasticity decreases with age",
    "- Men kan fremmes gjennom:": "- But can be promoted through:",
    "  - Fysisk aktivitet": "  - Physical activity",
    "  - Mental stimulering": "  - Mental stimulation",
    "  - Sosial interaksjon": "  - Social interaction",
    "  - Ny læring": "  - New learning",
    "#### **Psykiske lidelser**": "#### **Mental Disorders**",
    "- Depresjon: Redusert neurogenese og synaptisk plastisitet": "- Depression: Reduced neurogenesis and synaptic plasticity",
    "- PTSD: Forstyrret konsolidering av traumatiske minner": "- PTSD: Disturbed consolidation of traumatic memories",
    "- Schizofreni: Endringer i synaptisk funksjon og nevroplastisitet": "- Schizophrenia: Changes in synaptic function and neuroplasticity",
    "#### Sammenligning: Biologisk vs Kunstig Læring": "#### Comparison: Biological vs Artificial Learning",
    "| Aspekt | Biologisk (Hjernen) | Kunstig (Neurale Nettverk) |": "| Aspect | Biological (Brain) | Artificial (Neural Networks) |",
    "| **Læringsmekanisme** | Synaptisk plastisitet | Gradient descent |": "| **Learning Mechanism** | Synaptic plasticity | Gradient descent |",
    "| **Tidsskala** | Millisekunder til år | Sekunder til timer |": "| **Time Scale** | Milliseconds to years | Seconds to hours |",
    "| **Energiforbruk** | ~20W (hele hjernen) | Varierer kraftig - ved trening av modeller fra 100 W (små forskningsmodeller) til megawatt (de største modellene) |": "| **Energy Consumption** | ~20W (whole brain) | Varies greatly - from 100 W (small research models) to megawatts (largest models) during training |",
    "| **Robusthet** | Høyt toleranse for feil | Kan være følsom |": "| **Robustness** | High fault tolerance | Can be sensitive |",
    "| **Adaptabilitet** | Kontinuerlig læring | Ofte batch-læring |": "| **Adaptability** | Continuous learning | Often batch learning |",
    "| **Forklarbarhet** | Kompleks, delvis forstått | Matematisk presis |": "| **Explainability** | Complex, partially understood | Mathematically precise |",
    "| **Kreativitet** | Høy kreativitet | Begrenset |": "| **Creativity** | High creativity | Limited |",
    "| **Generaliseringsgrad** | Utmerket | Varierer |": "| **Generalization Ability** | Excellent | Varies |",
    
    # Reinforcement Learning section
    "### **Forsterket Læring**: Belønning og Straff i Hjernen": "### **Reinforcement Learning**: Reward and Punishment in the Brain",
    "**Forsterket læring** (reinforcement learning, **RL**) er en fundamental læringsmekanisme som finnes både i biologiske og kunstige systemer. I hjernen skjer dette gjennom dopaminerge systemer som belønner ønsket oppførsel.": "**Reinforcement learning** (**RL**) is a fundamental learning mechanism found in both biological and artificial systems. In the brain, this occurs through dopaminergic systems that reward desired behavior.",
    "#### Biologiske Mekanismer for Forsterket Læring": "#### Biological Mechanisms for Reinforcement Learning",
    "**1. Dopaminerge Systemer**": "**1. Dopaminergic Systems**",
    "- **Ventral Tegmental Area (VTA)** og **Substantia Nigra** produserer dopamin": "- **Ventral Tegmental Area (VTA)** and **Substantia Nigra** produce dopamine",
    "- **Nucleus Accumbens** mottar dopamin og koder for belønning": "- **Nucleus Accumbens** receives dopamine and codes for reward",
    "- **Prefrontal Cortex** integrerer belønningsinformasjon for beslutningstaking": "- **Prefrontal Cortex** integrates reward information for decision-making",
    "**2. Belønningsprediksjon og Feil**": "**2. Reward Prediction and Error**",
    "- **Dopamin-nivåer** reflekterer forskjellen mellom forventet belønning og faktisk belønning": "- **Dopamine levels** reflect the difference between expected reward and actual reward",
    "- **Positive feil**: Høyere belønning enn forventet → Økt dopamin": "- **Positive errors**: Higher reward than expected → Increased dopamine",
    "- **Negative feil**: Lavere belønning enn forventet → Redusert dopamin": "- **Negative errors**: Lower reward than expected → Reduced dopamine",
    "**3. Temporal Difference Learning**": "**3. Temporal Difference Learning**",
    "- Hjernen lærer å forutsi fremtidige belønninger": "- The brain learns to predict future rewards",
    "- **Immediate reward**: Umiddelbar belønning": "- **Immediate reward**: Immediate reward",
    "- **Delayed reward**: Belønning som kommer senere": "- **Delayed reward**: Reward that comes later",
    "- **Discounting**: Fremtidige belønninger vektes lavere": "- **Discounting**: Future rewards are weighted lower",
    "Her er en mer presis formulering av belønningsprediksjon og feil:": "Here is a more precise formulation of reward prediction and error:",
    "**Belønningsprediksjon og Feil**": "**Reward Prediction and Error**",
    "**Dopamin-nivåer** reflekterer forskjellen mellom forventet og faktisk belønning:": "**Dopamine levels** reflect the difference between expected and actual reward:",
    "Hvor:": "Where:",
    "- $\\Delta R(t)$ = belønningsfeil (reward prediction error)": "- $\\Delta R(t)$ = reward prediction error",
    "- $R(t)$ = faktisk belønning ved tid $t$": "- $R(t)$ = actual reward at time $t$",
    "- $\\hat{R}(t)$ = forventet belønning ved tid $t$": "- $\\hat{R}(t)$ = expected reward at time $t$",
    "**Dopamin-respons** er proporsjonal med belønningsfeilen:": "**Dopamine response** is proportional to the reward prediction error:",
    "**Positive feil** (høyere belønning enn forventet):": "**Positive errors** (higher reward than expected):",
    "$\\Delta R(t) > 0 \\Rightarrow DA(t) > 0 \\text{ (økt dopamin)}$": "$\\Delta R(t) > 0 \\Rightarrow DA(t) > 0 \\text{ (increased dopamine)}$",
    "**Negative feil** (lavere belønning enn forventet):": "**Negative errors** (lower reward than expected):",
    "$\\Delta R(t) < 0 \\Rightarrow DA(t) < 0 \\text{ (redusert dopamin)}$": "$\\Delta R(t) < 0 \\Rightarrow DA(t) < 0 \\text{ (reduced dopamine)}$",
    "- $\\gamma$ = diskonteringsfaktor (0 < γ ≤ 1)": "- $\\gamma$ = discount factor (0 < γ ≤ 1)",
    "- $\\hat{V}(s_t)$ = forventet verdi av tilstand $s_t$*****": "- $\\hat{V}(s_t)$ = expected value of state $s_t$*****",
    "Dette er kjernen i **Temporal Difference (TD) learning** som er grunnlaget for både biologisk og kunstig forsterket læring.": "This is the core of **Temporal Difference (TD) learning** which is the foundation for both biological and artificial reinforcement learning.",
    "#### Klinisk Relevans for Helse": "#### Clinical Relevance for Health",
    "**1. Avhengighet og Belønningssystemer**": "**1. Addiction and Reward Systems**",
    "- **Substansmisbruk** kaprer naturlige belønningssystemer": "- **Substance abuse** hijacks natural reward systems",
    "- **Toleranse**: Økt behov for stimulus for samme belønningsfølelse": "- **Tolerance**: Increased need for stimulus for the same reward feeling",
    "- **Avhengighet**: Kompulsiv oppførsel til tross for negative konsekvenser": "- **Addiction**: Compulsive behavior despite negative consequences",
    "**2. Læring og Rehabilitering**": "**2. Learning and Rehabilitation**",
    "- **Positiv forsterkning** fremmer ønsket oppførsel": "- **Positive reinforcement** promotes desired behavior",
    "- **Negativ forsterkning** reduserer uønsket oppførsel": "- **Negative reinforcement** reduces undesired behavior",
    "- **Shaping**: Gradvis tilnærming til målferdigheter": "- **Shaping**: Gradual approach to target skills",
    "**3. Klinisk Anvendelse**": "**3. Clinical Application**",
    "- **Kognitiv atferdsterapi (CBT)**: Bruker prinsipper for forsterket læring": "- **Cognitive Behavioral Therapy (CBT)**: Uses principles of reinforcement learning",
    "- **Motivasjonelle intervjuer**: Forsterker endringsorientert oppførsel": "- **Motivational interviewing**: Reinforces change-oriented behavior",
    "- **Gamification**: Bruker belønningssystemer i behandling": "- **Gamification**: Uses reward systems in treatment",
    "#### Sammenligning: Hjernen vs. Kunstig Forsterket Læring": "#### Comparison: Brain vs. Artificial Reinforcement Learning",
    "| **Belønningssignal** | Dopamin | Numerisk reward |": "| **Reward Signal** | Dopamine | Numerical reward |",
    "| **Tidsskala** | Millisekunder | Diskret/episodisk |": "| **Time Scale** | Milliseconds | Discrete/episodic |",
    "| **Eksplorering** | Nysgjerrighet, nyskapende | Epsilon-greedy******, UCB****** |": "| **Exploration** | Curiosity, novelty-seeking | Epsilon-greedy******, UCB****** |",
    "| **Minne** | Hippocampus + Neocortex | Experience replay |": "| **Memory** | Hippocampus + Neocortex | Experience replay |",
    "| **Generalisering** | Høy | Avhenger av representasjon |": "| **Generalization** | High | Depends on representation |",
    "**Viktig for Helsepersonell:**": "**Important for Healthcare Professionals:**",
    "- Forstå at **motivasjon** og **belønning** er fundamentale læringsmekanismer": "- Understand that **motivation** and **reward** are fundamental learning mechanisms",
    "- **AI-systemer** kan bruke liknende prinsipper for å lære optimal oppførsel": "- **AI systems** can use similar principles to learn optimal behavior",
    "- **Klinisk relevans** for behandling av avhengighet og atferdsendring": "- **Clinical relevance** for treatment of addiction and behavioral change",
    
    # State explanation
    "**(*)** Hva menes med tilstand $s_t$ ?": "**(*)** What does state $s_t$ mean?",
    '"Tilstand $s_t$" representerer forskjellige ting i hjernen versus AI, men begge har samme grunnleggende funksjon.': '"State $s_t$" represents different things in the brain versus AI, but both have the same fundamental function.',
    "### I Hjernen (Biologisk)": "### In the Brain (Biological)",
    "**Tilstand $s_t$** representerer den **nevrale aktivitetstilstanden** i relevante hjerneområder:": "**State $s_t$** represents the **neural activity state** in relevant brain regions:",
    "#### Eksempler på tilstander:": "#### Examples of states:",
    '- **Sensorisk tilstand**: "Jeg ser mat" (visuell cortex aktivitet)': '- **Sensory state**: "I see food" (visual cortex activity)',
    '- **Motivasjonell tilstand**: "Jeg er sulten" (hypothalamus aktivitet)': '- **Motivational state**: "I am hungry" (hypothalamus activity)',
    '- **Spatial tilstand**: "Jeg er i kjøkkenet" (hippocampus sted-celler)': '- **Spatial state**: "I am in the kitchen" (hippocampus place cells)',
    '- **Emosjonell tilstand**: "Jeg føler meg glad" (limbisk system aktivitet)': '- **Emotional state**: "I feel happy" (limbic system activity)',
    '- **Motorisk tilstand**: "Jeg rekker ut hånden" (motor-cortex aktivitet)': '- **Motor state**: "I am reaching out my hand" (motor cortex activity)',
    "#### Konkret eksempel:": "#### Concrete example:",
    "Når du lærer å finne mat i kjøkkenet:": "When you learn to find food in the kitchen:",
    '- $s_t$ = "Jeg står i kjøkkenet og ser kjøleskapet"': '- $s_t$ = "I am standing in the kitchen and see the refrigerator"',
    '- $s_{t+1}$ = "Jeg har åpnet kjøleskapet og ser mat"': '- $s_{t+1}$ = "I have opened the refrigerator and see food"',
    '- $\\hat{V}(s_t)$ = "Hvor mye belønning forventer jeg fra denne situasjonen?"': '- $\\hat{V}(s_t)$ = "How much reward do I expect from this situation?"',
    "### I AI (Kunstig)": "### In AI (Artificial)",
    "**Tilstand $s_t$** representerer den **digitale representasjonen** av miljøet:": "**State $s_t$** represents the **digital representation** of the environment:",
    '- **Spill**: "Spilleren er på posisjon (x,y) med 3 liv igjen"': '- **Game**: "The player is at position (x,y) with 3 lives remaining"',
    '- **Robot**: "Roboten er 2 meter fra målet, peker nord, har 50% batteri"': '- **Robot**: "The robot is 2 meters from the target, facing north, has 50% battery"',
    '- **Medisinsk AI**: "Pasient har temperatur 38.5°C, puls 90, blodtrykk 140/90"': '- **Medical AI**: "Patient has temperature 38.5°C, pulse 90, blood pressure 140/90"',
    '- **Finansiell AI**: "Aksjekurs er 850 kr, volum er 500.000, RSI (Relativ Styrke Indeks) er 65" <br>': '- **Financial AI**: "Stock price is 850 kr, volume is 500,000, RSI (Relative Strength Index) is 65" <br>',
    '       (e.g., "Equinor-aksjen har steget 2% i dag, handelsvolumet er over gjennomsnittet")': '       (e.g., "Equinor stock has risen 2% today, trading volume is above average")',
    "En AI som lærer å spille Pac-Man:": "An AI learning to play Pac-Man:",
    '- $s_t$ = "Pac-Man er på posisjon (10,5), spøkelse på posisjon (8,3), 3 prikker igjen"': '- $s_t$ = "Pac-Man is at position (10,5), ghost at position (8,3), 3 dots remaining"',
    '- $s_{t+1}$ = "Pac-Man spiste en prikk, nå 2 prikker igjen"': '- $s_{t+1}$ = "Pac-Man ate a dot, now 2 dots remaining"',
    '- $\\hat{V}(s_t)$ = "Hvor mange poeng forventer AI-en fra denne posisjonen?"': '- $\\hat{V}(s_t)$ = "How many points does the AI expect from this position?"',
    "### Sammenligning": "### Comparison",
    "| Aspekt | Hjernen | AI |": "| Aspect | Brain | AI |",
    "| **Representasjon** | Nevral aktivitet | Numeriske verdier |": "| **Representation** | Neural activity | Numerical values |",
    "| **Kompleksitet** | ~86 milliarder nevroner | Begrenset av beregningskraft |": "| **Complexity** | ~86 billion neurons | Limited by computational power |",
    "| **Kontinuerlig** | Analog, flytende | Ofte diskret |": "| **Continuous** | Analog, fluid | Often discrete |",
    "| **Kontekst** | Rik, multimodal | Avhengig av sensorer |": "| **Context** | Rich, multimodal | Dependent on sensors |",
    "| **Minne** | Hippocampus + Neocortex | Experience replay buffer**#** |": "| **Memory** | Hippocampus + Neocortex | Experience replay buffer**#** |",
    "### Klinisk Relevans": "### Clinical Relevance",
    "**For helsepersonell** er dette viktig fordi:": "**For healthcare professionals** this is important because:",
    "1. **Pasienttilstander**: AI kan lære å forutsi utfall basert på pasientdata": "1. **Patient states**: AI can learn to predict outcomes based on patient data",
    "2. **Behandlingsvalg**: Systemer kan lære optimal behandling for ulike tilstander": "2. **Treatment choices**: Systems can learn optimal treatment for different states",
    "3. **Diagnostikk**: AI kan gjenkjenne mønstre i pasienttilstander": "3. **Diagnostics**: AI can recognize patterns in patient states",
    "**Eksempel**: En AI som lærer å dosere insulin:": "**Example**: An AI learning to dose insulin:",
    '- $s_t$ = "Blodsukker: 180 mg/dL, tid: 14:00, siste måltid: 2 timer siden"': '- $s_t$ = "Blood sugar: 180 mg/dL, time: 14:00, last meal: 2 hours ago"',
    '- $\\hat{V}(s_t)$ = "Forventet belønning (stabil blodsukker) fra denne tilstanden"': '- $\\hat{V}(s_t)$ = "Expected reward (stable blood sugar) from this state"',
    "- AI lærer å forutsi hvilke doser som gir best resultat for ulike tilstander": "- AI learns to predict which doses give the best result for different states",
    'Tilstanden er altså en "snapshot" av situasjonen som systemet bruker for å ta beslutninger og lære fra resultatene.': 'The state is thus a "snapshot" of the situation that the system uses to make decisions and learn from results.',
    
    # Experience Replay Buffer
    '**(#)** Hva er "Experience replay buffer"?': '**(#)** What is an "Experience Replay Buffer"?',
    "**Experience Replay Buffer** (erfaringsgjenbruk) er en viktig teknikk i forsterket læring som hjelper AI-systemer å lære mer effektivt ved å lagre og gjenbruke tidligere opplevelser.": "**Experience Replay Buffer** is an important technique in reinforcement learning that helps AI systems learn more effectively by storing and reusing past experiences.",
    "#### Hva er det?": "#### What is it?",
    "Experience Replay Buffer er en **datastruktur** som lagrer:": "Experience Replay Buffer is a **data structure** that stores:",
    "- **Tilstand** ($s_t$): Hva som skjedde": "- **State** ($s_t$): What happened",
    "- **Handling** ($a_t$): Hva AI-en gjorde": "- **Action** ($a_t$): What the AI did",
    "- **Belønning** ($r_t$): Hvor bra det gikk": "- **Reward** ($r_t$): How well it went",
    "- **Neste tilstand** ($s_{t+1}$): Hva som skjedde etterpå": "- **Next state** ($s_{t+1}$): What happened afterwards",
    "#### Hvordan fungerer det?": "#### How does it work?",
    '##### 1. **Lagring**:': '##### 1. **Storage**:',
    '##### 2. **Trening**:': '##### 2. **Training**:',
    "- I stedet for å lære bare fra siste opplevelse": "- Instead of learning only from the last experience",
    "- AI-en velger **tilfeldige** opplevelser fra bufferen": "- The AI selects **random** experiences from the buffer",
    "- Dette bryter korrelasjonen mellom påfølgende opplevelser": "- This breaks the correlation between consecutive experiences",
    '##### 3. **Fordeler**:': '##### 3. **Benefits**:',
    "- **Stabilisering**: Reduserer variasjon i læring": "- **Stabilization**: Reduces variance in learning",
    "- **Efektivitet**: Gjenbruker tidligere data": "- **Efficiency**: Reuses previous data",
    "- **Diversitet**: Lærer fra mange forskjellige situasjoner": "- **Diversity**: Learns from many different situations",
    "#### Praktisk eksempel:": "#### Practical example:",
    "**En AI som lærer å spille et spill**:": "**An AI learning to play a game**:",
    "- **Buffer**: Lagrer 10.000 tidligere spillrunder": "- **Buffer**: Stores 10,000 previous game rounds",
    "- **Trening**: Velger tilfeldig 32 opplevelser fra bufferen": "- **Training**: Randomly selects 32 experiences from the buffer",
    "- **Læring**: Bruker disse til å oppdatere strategien": "- **Learning**: Uses these to update the strategy",
    "#### Sammenligning med Biologisk Minne": "#### Comparison with Biological Memory",
    "| Aspekt | Experience Replay | Hjernen |": "| Aspect | Experience Replay | Brain |",
    "| **Lagring** | Digital buffer | Hippocampus + Neocortex |": "| **Storage** | Digital buffer | Hippocampus + Neocortex |",
    "| **Tilgang** | Tilfeldig sampling | Assosiativ gjenkalling |": "| **Access** | Random sampling | Associative recall |",
    "| **Kapasitet** | Begrenset størrelse | Praktisk ubegrenset |": "| **Capacity** | Limited size | Practically unlimited |",
    "| **Konsolidering** | Ingen | Langtidshukommelse |": "| **Consolidation** | None | Long-term memory |",
    "| **Emosjoner** | Ingen | Sterk påvirkning |": "| **Emotions** | None | Strong influence |",
    "**For helsepersonell** er dette relevant fordi:": "**For healthcare professionals** this is relevant because:",
    "##### 1. **Medisinske AI-systemer**:": "##### 1. **Medical AI Systems**:",
    "- **Diagnostikk**: Lærer fra tusenvis av pasienttilfeller": "- **Diagnostics**: Learns from thousands of patient cases",
    "- **Behandling**: Bruker erfaring fra liknende pasienter": "- **Treatment**: Uses experience from similar patients",
    "- **Prediksjon**: Forutser utfall basert på historiske data": "- **Prediction**: Predicts outcomes based on historical data",
    "##### 2. **Klinisk beslutningstaking**:": "##### 2. **Clinical Decision Making**:",
    "- **Pattern recognition**: Gjenkjenner mønstre i pasientdata": "- **Pattern recognition**: Recognizes patterns in patient data",
    "- **Risk assessment**: Vurderer risiko basert på tidligere tilfeller": "- **Risk assessment**: Assesses risk based on previous cases",
    "- **Treatment optimization**: Finner beste behandling basert på erfaring": "- **Treatment optimization**: Finds best treatment based on experience",
    "##### 3. **Eksempel i praksis**:": "##### 3. **Example in Practice**:",
    "En AI som lærer å diagnostisere hjerteinfarkt:": "An AI learning to diagnose heart attacks:",
    "- **Buffer**: Lagrer 50.000 pasienttilfeller med EKG, symptomer, og diagnose": "- **Buffer**: Stores 50,000 patient cases with ECG, symptoms, and diagnosis",
    "- **Trening**: Velger tilfeldig 100 tilfeller for hver treningsrunde": "- **Training**: Randomly selects 100 cases for each training round",
    "- **Læring**: Forbedrer diagnostisk nøyaktighet over tid": "- **Learning**: Improves diagnostic accuracy over time",
    '**Viktig poeng**: Experience Replay, inspirert fra menneskelig læring,  hjelper AI-en å lære ved å "reflektere" over tidligere erfaringer og trekke lærdommer fra dem, i stedet for bare å reagere på det som skjer akkurat nå.': '**Key point**: Experience Replay, inspired by human learning, helps the AI learn by "reflecting" on past experiences and drawing lessons from them, instead of just reacting to what is happening right now.',
    
    # Epsilon-greedy and UCB
    "**(**)** Hva betyr **Epsilon-greedy** og **UCB** i konteksten av forsterket læring (reinforcement learning?": "**(**)** What do **Epsilon-greedy** and **UCB** mean in the context of reinforcement learning?",
    "Dette er algoritmer som brukes for å balansere mellom **eksplorering** (undersøkelse) og **eksploitering** (utnyttelse) i AI-systemer.": "These are algorithms used to balance between **exploration** and **exploitation** in AI systems.",
    "#### Epsilon-greedy (ε-greedy)": "#### Epsilon-greedy (ε-greedy)",
    "**Epsilon-greedy** er en enkel men effektiv strategi for å håndtere **eksplorering vs eksploitering**-dilemmaet:": "**Epsilon-greedy** is a simple but effective strategy for handling the **exploration vs exploitation** dilemma:",
    "##### Hvordan det fungerer:": "##### How it works:",
    "- **Eksploitering (1-ε)**: Velg den handlingen som for øyeblikket ser best ut (høyest forventet belønning)": "- **Exploitation (1-ε)**: Choose the action that currently looks best (highest expected reward)",
    "- **Eksplorering (ε)**: Velg en tilfeldig handling for å utforske nye muligheter": "- **Exploration (ε)**: Choose a random action to explore new possibilities",
    "##### Eksempel:": "##### Example:",
    "- Hvis ε = 0.1 (10%), vil systemet:": "- If ε = 0.1 (10%), the system will:",
    "  - 90% av tiden velge den beste kjente handlingen": "  - 90% of the time choose the best known action",
    "  - 10% av tiden velge en tilfeldig handling": "  - 10% of the time choose a random action",
    "##### Praktisk eksempel:": "##### Practical example:",
    "En AI som lærer å spille et spill:": "An AI learning to play a game:",
    "- **Eksploitering**: Bruk den strategien som har gitt best resultat så langt": "- **Exploitation**: Use the strategy that has given the best result so far",
    "- **Eksplorering**: Prøv en ny strategi for å se om den kan være enda bedre": "- **Exploration**: Try a new strategy to see if it might be even better",
    "**UCB** er en mer sofistikert strategi som bruker statistisk teori for å balansere eksplorering og eksploitering:": "**UCB** is a more sophisticated strategy that uses statistical theory to balance exploration and exploitation:",
    'UCB velger handlingen med høyest **"upper confidence bound"** - en kombinasjon av:': 'UCB chooses the action with the highest **"upper confidence bound"** - a combination of:',
    "1. **Forventet belønning** (eksploitering)": "1. **Expected reward** (exploitation)",
    "2. **Usikkerhet** (eksplorering)": "2. **Uncertainty** (exploration)",
    "##### Formelen:": "##### The formula:",
    "- `Q(a)` = gjennomsnittlig belønning for handling a": "- `Q(a)` = average reward for action a",
    "- `c` = konfidensnivå (hvor mye eksplorering)": "- `c` = confidence level (how much exploration)",
    "- `t` = totalt antall forsøk": "- `t` = total number of attempts",
    "- `N(a)` = antall ganger handling a har blitt prøvd": "- `N(a)` = number of times action a has been tried",
    "En AI som lærer å velge mellom forskjellige behandlingsmetoder:": "An AI learning to choose between different treatment methods:",
    "- **Høy Q(a)**: Behandling som har gitt gode resultater": "- **High Q(a)**: Treatment that has given good results",
    "- **Høy usikkerhet**: Behandling som ikke er prøvd så ofte": "- **High uncertainty**: Treatment that has not been tried as often",
    "- **UCB velger**: Behandling med best kombinasjon av godt resultat og høy usikkerhet": "- **UCB chooses**: Treatment with best combination of good result and high uncertainty",
    "#### Sammenligning med Biologisk Læring": "#### Comparison with Biological Learning",
    "| Aspekt | Biologisk (Hjernen) | Epsilon-greedy | UCB |": "| Aspect | Biological (Brain) | Epsilon-greedy | UCB |",
    "| **Eksplorering** | Nysgjerrighet, spontan aktivitet | Tilfeldig valg | Statistisk usikkerhet |": "| **Exploration** | Curiosity, spontaneous activity | Random choice | Statistical uncertainty |",
    "| **Eksploitering** | Gjentakelse av vellykkede handlinger | Beste kjente handling | Høyest forventet belønning |": "| **Exploitation** | Repetition of successful actions | Best known action | Highest expected reward |",
    "| **Adaptabilitet** | Dynamisk basert på kontekst | Fast ε-verdi | Dynamisk basert på usikkerhet |": "| **Adaptability** | Dynamic based on context | Fixed ε-value | Dynamic based on uncertainty |",
    "| **Kompleksitet** | Høy (mange faktorer) | Lav | Medium |": "| **Complexity** | High (many factors) | Low | Medium |",
    "1. **Behandlingsvalg**: AI-systemer kan bruke disse strategiene for å lære optimal behandling": "1. **Treatment choices**: AI systems can use these strategies to learn optimal treatment",
    "2. **Kliniske forsøk**: Prinsippene ligner på adaptive kliniske forsøk": "2. **Clinical trials**: The principles are similar to adaptive clinical trials",
    "3. **Personlig medisin**: Systemer kan lære individuelt optimale behandlinger": "3. **Personalized medicine**: Systems can learn individually optimal treatments",
    "**Eksempel i praksis**:": "**Example in practice**:",
    "- En AI som lærer å dosere medisin kan bruke UCB for å balansere mellom å bruke doser som har fungert godt og å prøve nye doser for å finne enda bedre alternativer.": "- An AI learning to dose medication can use UCB to balance between using doses that have worked well and trying new doses to find even better alternatives.",
    "Disse algoritmene hjelper AI-systemer å lære på en måte som ligner på hvordan mennesker balanserer mellom å bruke det vi vet fungerer og å utforske nye muligheter.": "These algorithms help AI systems learn in a way that resembles how humans balance between using what we know works and exploring new possibilities.",
    
    # From Biology to AI
    "##  🤖 2. Fra Biologi til Kunstig Intelligens": "##  🤖 2. From Biology to Artificial Intelligence",
    "Nå som vi har fått innblikk i biologisk læring, kan vi se hvordan kunstige nevrale nettverk inspirert av hjernen fungerer.": "Now that we have gained insight into biological learning, we can see how artificial neural networks inspired by the brain work.",
    "### Teoretisk Fundament": "### Theoretical Foundation",
    "### Hvordan Lærer et Kunstig Nevralt Nettverk?": "### How Does an Artificial Neural Network Learn?",
    "Læring i kunstige nevrale nettverk skjer gjennom **optimalisering** - vi justerer vektene for å minimere feilen:": "Learning in artificial neural networks occurs through **optimization** - we adjust the weights to minimize error:",
    "1. **Fremover-pass**: Beregn prediksjon fra input": "1. **Forward pass**: Compute prediction from input",
    '2. **Beregn feil**: Sammenlign prediksjon med "sannhet"': '2. **Calculate error**: Compare prediction with "ground truth"',
    "3. **Bakover-pass**: Beregn gradienter (hvordan endre vekter)": "3. **Backward pass**: Calculate gradients (how to change weights)",
    "4. **Oppdater vekter**: Juster vekter i retning som reduserer feil": "4. **Update weights**: Adjust weights in direction that reduces error",
    "5. **Gjenta**: Fortsett til konvergens": "5. **Repeat**: Continue until convergence",
    "### Matematisk Formulering": "### Mathematical Formulation",
    "**Tap-funksjon**: L(θ) = Σ tap(f(xᵢ, θ), yᵢ)": "**Loss function**: L(θ) = Σ loss(f(xᵢ, θ), yᵢ)",
    "**Gradient Nedstigning**: θ ← θ - α∇L(θ)": "**Gradient Descent**: θ ← θ - α∇L(θ)",
    "### Symboldefinisjoner": "### Symbol Definitions",
    "**Tap-funksjonen** måler hvor godt modellen vår gjør det:": "**The loss function** measures how well our model is doing:",
    "- **L(θ)** = Total tap for modellen med parametere θ": "- **L(θ)** = Total loss for the model with parameters θ",
    "- **Σ** = Sum over alle eksempler i treningssettet": "- **Σ** = Sum over all examples in the training set",
    "- **tap()** = Tap-funksjon som måler feil for ett eksempel": "- **loss()** = Loss function that measures error for one example",
    "- **f(xᵢ, θ)** = Modellens prediksjon for input xᵢ med parametere θ": "- **f(xᵢ, θ)** = Model's prediction for input xᵢ with parameters θ",
    "- **xᵢ** = Input-eksempel nummer i (f.eks. pasientdata)": "- **xᵢ** = Input example number i (e.g., patient data)",
    "- **yᵢ** = Sann verdi for eksempel i (f.eks. diagnose)": "- **yᵢ** = True value for example i (e.g., diagnosis)",
    "- **θ** = Alle modellparametere (vekter og bias)": "- **θ** = All model parameters (weights and biases)",
    "**Gradient Nedstigning** oppdaterer parametrene:": "**Gradient Descent** updates the parameters:",
    "- **α** = Læringsrate (hvor store steg vi tar)": "- **α** = Learning rate (how large steps we take)",
    "- **∇L(θ)** = Gradient av tap-funksjonen (retning for endring)": "- **∇L(θ)** = Gradient of the loss function (direction for change)",
    "- **←** = Oppdatering (ny verdi blir til venstre side)": "- **←** = Update (new value becomes left side)",
    '### Eksempler på Tap-funksjoner ("Loss function")': "### Examples of Loss Functions",
    "Tap-funksjonen **tap()** måler hvor feil modellens prediksjon er. Her er vanlige eksempler:": "The loss function **loss()** measures how wrong the model's prediction is. Here are common examples:",
    "#### 1. **Mean Squared Error (MSE)** - For Regresjon": "#### 1. **Mean Squared Error (MSE)** - For Regression",
    "tap(y_true, y_pred) = (y_true - y_pred)²": "loss(y_true, y_pred) = (y_true - y_pred)²",
    "**Medisinsk eksempel**: Prediksjon av blodtrykk": "**Medical example**: Prediction of blood pressure",
    "- Hvis sann verdi er 120 mmHg og modellen predikerer 125 mmHg": "- If true value is 120 mmHg and the model predicts 125 mmHg",
    "- Tap = (120 - 125)² = 25": "- Loss = (120 - 125)² = 25",
    "#### 2. **Cross-Entropy Loss** - For Klassifikasjon": "#### 2. **Cross-Entropy Loss** - For Classification",
    "tap(y_true, y_pred) = -y_true × log(y_pred)": "loss(y_true, y_pred) = -y_true × log(y_pred)",
    "**Medisinsk eksempel**: Diagnose av sykdom (0=frisk, 1=syk)": "**Medical example**: Diagnosis of disease (0=healthy, 1=sick)",
    "- Hvis pasient er syk (y_true=1) og modellen predikerer 90% sannsynlighet for sykdom": "- If patient is sick (y_true=1) and the model predicts 90% probability of disease",
    "- Tap = -1 × log(0.9) = 0.105 (lavt tap = god prediksjon)": "- Loss = -1 × log(0.9) = 0.105 (low loss = good prediction)",
    "- Hvis modellen predikerer 10% sannsynlighet for sykdom": "- If the model predicts 10% probability of disease",
    "- Tap = -1 × log(0.1) = 2.303 (høyt tap = dårlig prediksjon)": "- Loss = -1 × log(0.1) = 2.303 (high loss = poor prediction)",
    "#### 3. **Binary Cross-Entropy** - For Binær Klassifikasjon": "#### 3. **Binary Cross-Entropy** - For Binary Classification",
    "tap(y_true, y_pred) = -[y_true×log(y_pred) + (1-y_true)×log(1-y_pred)]": "loss(y_true, y_pred) = -[y_true×log(y_pred) + (1-y_true)×log(1-y_pred)]",
    "**Medisinsk eksempel**: Prediksjon av hjertinfarkt": "**Medical example**: Prediction of heart attack",
    "- Frisk pasient (y_true=0) med 20% risiko: tap = -[0×log(0.2) + 1×log(0.8)] = 0.223": "- Healthy patient (y_true=0) with 20% risk: loss = -[0×log(0.2) + 1×log(0.8)] = 0.223",
    "- Syk pasient (y_true=1) med 80% risiko: tap = -[1×log(0.8) + 0×log(0.2)] = 0.223": "- Sick patient (y_true=1) with 80% risk: loss = -[1×log(0.8) + 0×log(0.2)] = 0.223",
    "#### 4. **Hinge Loss** - For Support Vector Machines": "#### 4. **Hinge Loss** - For Support Vector Machines",
    "tap(y_true, y_pred) = max(0, 1 - y_true × y_pred)": "loss(y_true, y_pred) = max(0, 1 - y_true × y_pred)",
    "**Medisinsk eksempel**: Klassifisering av kreftstadier": "**Medical example**: Classification of cancer stages",
    "- Hvis sann klasse er +1 og modellen predikerer +0.8": "- If true class is +1 and the model predicts +0.8",
    "- Tap = max(0, 1 - 1×0.8) = max(0, 0.2) = 0.2": "- Loss = max(0, 1 - 1×0.8) = max(0, 0.2) = 0.2",
    "#### 5. **Huber Loss** - Robust mot Uteliggere": "#### 5. **Huber Loss** - Robust Against Outliers",
    "tap(y_true, y_pred) = {": "loss(y_true, y_pred) = {",
    "    0.5 × (y_true - y_pred)²     hvis |y_true - y_pred| ≤ δ": "    0.5 × (y_true - y_pred)²     if |y_true - y_pred| ≤ δ",
    "    δ × |y_true - y_pred| - 0.5 × δ²  ellers": "    δ × |y_true - y_pred| - 0.5 × δ²  otherwise",
    "**Medisinsk eksempel**: Prediksjon av blodtrykk med uteliggere": "**Medical example**: Prediction of blood pressure with outliers",
    "- **δ (delta)** = Terskelverdi som bestemmer når vi bytter fra kvadratisk til lineær tap": "- **δ (delta)** = Threshold value that determines when to switch from quadratic to linear loss",
    "- **Små feil** (≤ δ): Bruker kvadratisk tap som MSE": "- **Small errors** (≤ δ): Uses quadratic loss like MSE",
    "- **Store feil** (> δ): Bruker lineær tap som MAE": "- **Large errors** (> δ): Uses linear loss like MAE",
    "**Praktisk eksempel** med δ = 10:": "**Practical example** with δ = 10:",
    "- Feil på 5 mmHg: tap = 0.5 × 5² = 12.5 (kvadratisk)": "- Error of 5 mmHg: loss = 0.5 × 5² = 12.5 (quadratic)",
    "- Feil på 15 mmHg: tap = 10 × 15 - 0.5 × 10² = 100 (lineær)": "- Error of 15 mmHg: loss = 10 × 15 - 0.5 × 10² = 100 (linear)",
    "**Fordeler**:": "**Benefits**:",
    "- **Robust mot uteliggere**: Store feil straffes ikke så hardt som med MSE": "- **Robust against outliers**: Large errors are not penalized as harshly as with MSE",
    "- **Glatt overgang**: Kontinuerlig funksjon uten knekk": "- **Smooth transition**: Continuous function without kinks",
    "- **Balanserer MSE og MAE**: Kombinerer beste egenskaper fra begge": "- **Balances MSE and MAE**: Combines best properties from both",
    "### Hvorfor Forskjellige Tap-funksjoner?": "### Why Different Loss Functions?",
    "- **MSE**: Best for kontinuerlige verdier (blodtrykk, temperatur)": "- **MSE**: Best for continuous values (blood pressure, temperature)",
    "- **Cross-Entropy**: Best for sannsynligheter og klassifikasjon": "- **Cross-Entropy**: Best for probabilities and classification",
    "- **Hinge Loss**: Best for margin-baserte klassifikatorer": "- **Hinge Loss**: Best for margin-based classifiers",
    "- **Huber Loss**: Robust mot uteliggere (kombinerer MSE og MAE)": "- **Huber Loss**: Robust against outliers (combines MSE and MAE)",
    "### Praktisk Betydning": "### Practical Significance",
    "Valg av tap-funksjon påvirker:": "Choice of loss function affects:",
    "- **Hvor raskt** modellen lærer": "- **How quickly** the model learns",
    "- **Hvilke feil** som blir mest straffet": "- **Which errors** are most penalized",
    "- **Robusthet** mot uteliggere i dataene": "- **Robustness** against outliers in the data",
    "- **Balansen** mellom falske positive og falske negative": "- **The balance** between false positives and false negatives",
}

def translate_cell(cell_content):
    """Translate Norwegian content to English"""
    result = cell_content
    for norwegian, english in translations.items():
        result = result.replace(norwegian, english)
    return result

# Process each cell
for cell in notebook['cells']:
    if cell['cell_type'] == 'markdown':
        # Join the source lines, translate, and split back
        content = ''.join(cell['source'])
        translated = translate_cell(content)
        cell['source'] = [line + '\n' if i < len(translated.split('\n')) - 1 else line 
                         for i, line in enumerate(translated.split('\n'))]
    elif cell['cell_type'] == 'code':
        # Translate comments in code cells
        new_source = []
        for line in cell['source']:
            translated_line = translate_cell(line)
            new_source.append(translated_line)
        cell['source'] = new_source

# Save the translated notebook
with open('B2-learning-in-nn.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=2)

print("Translation complete!")

