#!/usr/bin/env python3
"""Script to translate remaining cells (23-29) in B2-learning-in-nn.ipynb"""

import json

with open('B2-learning-in-nn.ipynb', 'r', encoding='utf-8') as f:
    notebook = json.load(f)

translations = {
    # Cell 23 - Gradient descent vs backpropagation
    "### Hva er da forskjellen mellom Gradient Nedstigning (omtalt tidligere) og Backpropagation": "### What is the difference between Gradient Descent (discussed earlier) and Backpropagation",
    '#### 🎯 **Gradient Nedstigning: "Hvor skal vi gå?"**': '#### 🎯 **Gradient Descent: "Where should we go?"**',
    "**Gradient nedstigning** er **optimaliseringsalgoritmen** - den bestemmer **hvilken retning** vi skal gå for å finne det beste resultatet.": "**Gradient descent** is the **optimization algorithm** - it determines **which direction** we should go to find the best result.",
    "**Hva den gjør:**": "**What it does:**",
    "- Beregner **retningen** med størst stigning (gradienten)": "- Calculates the **direction** with the greatest slope (the gradient)",
    "- Går i **motsatt retning** for å finne minimum": "- Goes in the **opposite direction** to find the minimum",
    "- Oppdaterer **alle parametere** samtidig": "- Updates **all parameters** simultaneously",
    "- **Formel**: θ ← θ - α∇L(θ)": "- **Formula**: θ ← θ - α∇L(θ)",
    "**Geografisk analogi:**": "**Geographic analogy:**",
    "Som å være på et fjell og finne dalen ved å følge terrenget nedover. Du vet ikke nøyaktig hvor dalen er, men du følger retningen som går nedover.": "Like being on a mountain and finding the valley by following the terrain downhill. You don't know exactly where the valley is, but you follow the direction that goes down.",
    '#### ⚡ **Backpropagation: "Hvordan beregner vi retningen?"**': '#### ⚡ **Backpropagation: "How do we calculate the direction?"**',
    "**Backpropagation** er **beregningsmetoden** - den finner ut **hvordan** hver vekt påvirker den totale feilen.": "**Backpropagation** is the **calculation method** - it figures out **how** each weight affects the total error.",
    "- Beregner **gradienter** for hver vekt i nettverket": "- Calculates **gradients** for each weight in the network",
    "- Bruker **kjerneregelen** fra kalkulus": "- Uses the **chain rule** from calculus",
    '- "Går bakover" gjennom nettverket': '- "Goes backward" through the network',
    "**Medisinsk analogi:**": "**Medical analogy:**",
    "Som å analysere hvilke faktorer som førte til en feil diagnose. Du går systematisk gjennom hver del av diagnostikken for å finne ut hva som må endres.": "Like analyzing which factors led to an incorrect diagnosis. You systematically go through each part of the diagnostics to find out what needs to be changed.",
    "#### 🔄 **Sammenhengen: To Sider av Samme Mynt**": "#### 🔄 **The Connection: Two Sides of the Same Coin**",
    "**Backpropagation** → **Gradient Nedstigning**": "**Backpropagation** → **Gradient Descent**",
    "1. **Backpropagation** beregner gradientene (hvor mye hver vekt påvirker feilen)": "1. **Backpropagation** calculates the gradients (how much each weight affects the error)",
    "2. **Gradient nedstigning** bruker disse gradientene for å oppdatere vektene": "2. **Gradient descent** uses these gradients to update the weights",
    "**Praktisk eksempel:**": "**Practical example:**",
    '- **Backpropagation**: "Vekt w1 påvirker feilen med -20, w2 med -30"': '- **Backpropagation**: "Weight w1 affects the error by -20, w2 by -30"',
    '- **Gradient nedstigning**: "La oss øke w1 med 2.0 og w2 med 3.0 for å redusere feilen"': '- **Gradient descent**: "Let\'s increase w1 by 2.0 and w2 by 3.0 to reduce the error"',
    "#### 📊 **Visuell Sammenligning**": "#### 📊 **Visual Comparison**",
    "| Aspekt | Gradient Nedstigning | Backpropagation |": "| Aspect | Gradient Descent | Backpropagation |",
    '| **Hovedoppgave** | Optimalisering | Beregning av gradienter |': '| **Main Task** | Optimization | Calculation of gradients |',
    '| **Spørsmål** | "Hvor skal vi gå?" | "Hvordan beregner vi retningen?" |': '| **Question** | "Where should we go?" | "How do we calculate the direction?" |',
    "| **Input** | Gradienter | Nettverksarkitektur + feil |": "| **Input** | Gradients | Network architecture + error |",
    "| **Output** | Oppdaterte vekter | Gradienter for hver vekt |": "| **Output** | Updated weights | Gradients for each weight |",
    "| **Tidsskala** | Hver iterasjon | Hver iterasjon |": "| **Time Scale** | Each iteration | Each iteration |",
    "| **Matematikk** | Enkel subtraksjon | Kompleks derivasjon |": "| **Mathematics** | Simple subtraction | Complex differentiation |",
    "#### 🧠 **I Praksis: Hvordan de Arbeider Sammen**": "#### 🧠 **In Practice: How They Work Together**",
    "**Trinn 1: Fremover-pass**": "**Step 1: Forward Pass**",
    "- Nettverket gjør en prediksjon": "- The network makes a prediction",
    "- Vi beregner feilen": "- We calculate the error",
    "**Trinn 2: Backpropagation**": "**Step 2: Backpropagation**",
    "- Beregner hvordan hver vekt påvirker feilen": "- Calculates how each weight affects the error",
    "- Gir oss gradientene": "- Gives us the gradients",
    "**Trinn 3: Gradient nedstigning**": "**Step 3: Gradient Descent**",
    "- Bruker gradientene for å oppdatere vektene": "- Uses the gradients to update the weights",
    "- Går i retning som reduserer feilen": "- Goes in the direction that reduces the error",
    "**Trinn 4: Gjenta**": "**Step 4: Repeat**",
    "- Fortsett til nettverket har lært": "- Continue until the network has learned",
    "#### 🎯 **Hvorfor Dette er Viktig for Helsepersonell**": "#### 🎯 **Why This is Important for Healthcare Professionals**",
    "**Forståelse av AI-grenser:**": "**Understanding AI limitations:**",
    '- AI "lærer" ikke som mennesker': '- AI does not "learn" like humans',
    "- Det er matematiske algoritmer som optimaliserer parametere": "- They are mathematical algorithms that optimize parameters",
    "- **Backpropagation** er ikke biologisk plausibel": "- **Backpropagation** is not biologically plausible",
    "**Klinisk relevans:**": "**Clinical relevance:**",
    "- Hjelper å forstå hvorfor AI kan gjøre feil": "- Helps understand why AI can make mistakes",
    "- Viktig for å vurdere AI-systemers pålitelighet": "- Important for assessing the reliability of AI systems",
    "- Betydelig for implementering av AI i klinisk praksis": "- Significant for implementing AI in clinical practice",
    "#### 📚 **Oppsummering**": "#### 📚 **Summary**",
    "**Gradient nedstigning** og **backpropagation** er to deler av samme læringsprosess:": "**Gradient descent** and **backpropagation** are two parts of the same learning process:",
    '- **Backpropagation** = "Hvordan beregner vi retningen?"': '- **Backpropagation** = "How do we calculate the direction?"',
    '- **Gradient nedstigning** = "Hvor skal vi gå?"': '- **Gradient descent** = "Where should we go?"',
    "Uten backpropagation ville vi ikke vite hvilken retning å gå. Uten gradient nedstigning ville vi ikke kunne oppdatere vektene. Sammen lar de nevrale nettverk lære fra data og forbedre sine prediksjoner.": "Without backpropagation, we wouldn't know which direction to go. Without gradient descent, we couldn't update the weights. Together, they allow neural networks to learn from data and improve their predictions.",
    
    # Cell 24
    "_Jeg har hørt om batchvis oppdatering, hvordan kommer dette inn i spill?_": "_I have heard about batch updates, how does this come into play?_",
    
    # Cell 25 - Batch updates
    "Batchvis oppdatering er en viktig teknikk i maskinlæring som påvirker både gradient nedstigning og backpropagation.": "Batch update is an important technique in machine learning that affects both gradient descent and backpropagation.",
    "### 🍽️ **Batchvis Oppdatering: Hva er det?**": "### 🍽️ **Batch Update: What is it?**",
    "**Batch** = en gruppe eksempler (datapunkter, instanser, delmengder av treningsdata) som behandles samtidig<br>": "**Batch** = a group of examples (data points, instances, subsets of training data) that are processed simultaneously<br>",
    "**Batchvis oppdatering** = oppdaterer vektene basert på flere eksempler av gangen, ikke bare ett": "**Batch update** = updates the weights based on multiple examples at a time, not just one",
    "#### 📊 **Tre Typer Oppdatering**": "#### 📊 **Three Types of Updates**",
    "##### 1. **Stokastisk Gradient Nedstigning (SGD)**": "##### 1. **Stochastic Gradient Descent (SGD)**",
    "- **Batch størrelse**: 1": "- **Batch size**: 1",
    "- **Hvordan**: Oppdaterer vekter etter hvert eksempel": "- **How**: Updates weights after each example",
    "- **Fordel**: Rask oppdatering, kan lære fra nye data fort": "- **Advantage**: Fast update, can learn from new data quickly",
    '- **Ulempe**: Ustabil, kan "hoppe rundt" i parameterrommet': '- **Disadvantage**: Unstable, can "jump around" in parameter space',
    "##### 2. **Batch Gradient Nedstigning**": "##### 2. **Batch Gradient Descent**",
    "- **Batch størrelse**: Hele datasettet": "- **Batch size**: Entire dataset",
    "- **Hvordan**: Oppdaterer vekter etter å ha sett alle eksempler": "- **How**: Updates weights after seeing all examples",
    "- **Fordel**: Stabil, konvergerer til globalt minimum": "- **Advantage**: Stable, converges to global minimum",
    "- **Ulempe**: Tregt, krever mye minne": "- **Disadvantage**: Slow, requires a lot of memory",
    "##### 3. **Mini-batch Gradient Nedstigning** ⭐": "##### 3. **Mini-batch Gradient Descent** ⭐",
    "- **Batch størrelse**: 32-256 eksempler (typisk)": "- **Batch size**: 32-256 examples (typical)",
    "- **Hvordan**: Oppdaterer vekter etter hver mini-batch": "- **How**: Updates weights after each mini-batch",
    "- **Fordel**: Balanserer stabilitet og hastighet": "- **Advantage**: Balances stability and speed",
    "- **Ulempe**: Krever tuning av batch størrelse": "- **Disadvantage**: Requires tuning of batch size",
    "#### 🔄 **Hvordan Batchvis Oppdatering Fungerer**": "#### 🔄 **How Batch Update Works**",
    "##### **Fremover-pass for en Batch:**": "##### **Forward Pass for a Batch:**",
    "# For hver eksempel i batchen": "# For each example in the batch",
    "# Gjennomsnittlig tap for batchen": "# Average loss for the batch",
    "##### **Backpropagation for en Batch:**": "##### **Backpropagation for a Batch:**",
    "# Beregn gradienter for hele batchen": "# Calculate gradients for the entire batch",
    "# Gradientene er nå gjennomsnittet over alle eksempler i batchen": "# The gradients are now the average over all examples in the batch",
    "##### **Gradient Nedstigning med Batch:**": "##### **Gradient Descent with Batch:**",
    "# Oppdater vekter basert på gjennomsnittlige gradienter": "# Update weights based on average gradients",
    "#### 📈 **Visuell Sammenligning**": "#### 📈 **Visual Comparison**",
    "Forskjellen kan illustreres med et praktisk eksempel:": "The difference can be illustrated with a practical example:",
    "# Eksempel: Medisinsk diagnose med forskjellige batch størrelser": "# Example: Medical diagnosis with different batch sizes",
    "# SGD (batch_size = 1)": "# SGD (batch_size = 1)",
    "# Mini-batch (batch_size = 32)": "# Mini-batch (batch_size = 32)",
    "# Batch (batch_size = all_patients)": "# Batch (batch_size = all_patients)",
    "#### 🎯 **Hvorfor Batchvis Oppdatering er Viktig**": "#### 🎯 **Why Batch Update is Important**",
    "##### **1. Stabilitet**": "##### **1. Stability**",
    "- **Større batch** = mer stabil læring": "- **Larger batch** = more stable learning",
    "- **Mindre batch** = mer variasjon, men kan unngå lokale minima": "- **Smaller batch** = more variation, but can avoid local minima",
    "##### **2. Hastighet**": "##### **2. Speed**",
    "- **Større batch** = færre oppdateringer, men tregere per oppdatering": "- **Larger batch** = fewer updates, but slower per update",
    "- **Mindre batch** = flere oppdateringer, men raskere per oppdatering": "- **Smaller batch** = more updates, but faster per update",
    "##### **3. Minnebruk**": "##### **3. Memory Usage**",
    "- **Større batch** = krever mer minne": "- **Larger batch** = requires more memory",
    "- **Mindre batch** = krever mindre minne": "- **Smaller batch** = requires less memory",
    "##### **4. Generalisering** (*)": "##### **4. Generalization** (*)",
    "- **Større batch** = kan generalisere bedre": "- **Larger batch** = can generalize better",
    "- **Mindre batch** = kan unngå overtilpasning": "- **Smaller batch** = can avoid overfitting",
    "(*) Dette ser motstridende ut ved første øyekast, men:": "(*) This looks contradictory at first glance, but:",
    "### 🤔 **Tilsynelatende Motstrid: Generalisering vs Overtilpasning**": "### 🤔 **Apparent Contradiction: Generalization vs Overfitting**",
    "#### 📊 **Det Komplekse Forholdet mellom Batch Størrelse og Generalisering**": "#### 📊 **The Complex Relationship between Batch Size and Generalization**",
    "##### **1. Større Batch = Bedre Generalisering (generelt)**": "##### **1. Larger Batch = Better Generalization (generally)**",
    "**Hvorfor:**": "**Why:**",
    '- **Mer stabil læring**: Færre "hopp" i parameterrommet': '- **More stable learning**: Fewer "jumps" in parameter space',
    "- **Bedre gradient-estimater**: Gjennomsnitt over flere eksempler": "- **Better gradient estimates**: Average over more examples",
    "- **Mindre støy**: Enkelt eksempler påvirker mindre": "- **Less noise**: Individual examples affect less",
    "- **Mer konsistent**: Lærer fra representativt utvalg": "- **More consistent**: Learns from representative sample",
    "Med batch størrelse 128 lærer modellen fra 128 pasienter samtidig": "With batch size 128, the model learns from 128 patients simultaneously",
    "Enkel pasient med uvanlige symptomer påvirker læringen mindre": "A single patient with unusual symptoms affects learning less",
    "Modellen får et mer balansert bilde av sykdommen": "The model gets a more balanced picture of the disease",
    "##### **2. Mindre Batch = Kan Unngå Overfitting (i spesifikke tilfeller)**": "##### **2. Smaller Batch = Can Avoid Overfitting (in specific cases)**",
    '- **Mer støy**: Kan "hoppe ut" av lokale minima': '- **More noise**: Can "jump out" of local minima',
    "- **Bedre utforskning**: Undersøker parameterrommet mer": "- **Better exploration**: Explores parameter space more",
    '- **Mindre risiko for å "låse seg fast"**: Ikke overtilpasser til spesifikke mønstre': '- **Less risk of "getting stuck"**: Does not overfit to specific patterns',
    "Med batch størrelse 1 kan modellen lære fra hver enkelt pasient": "With batch size 1, the model can learn from each individual patient",
    "Kan oppdage sjeldne men viktige mønstre": "Can detect rare but important patterns",
    "Unngår å overtilpasse til vanlige tilfeller": "Avoids overfitting to common cases",
    "#### 🎯 **Den Viktige Distinksjonen**": "#### 🎯 **The Important Distinction**",
    "##### **Generalisering ≠ Overfitting-avverging**": "##### **Generalization ≠ Overfitting Prevention**",
    "**Generalisering** = Hvor godt modellen fungerer på nye data": "**Generalization** = How well the model works on new data",
    "**Overfitting-avverging** = Hvor godt modellen unngår å overtilpasse seg": "**Overfitting prevention** = How well the model avoids overfitting",
    "#### 📈 **Den U-formede Kurven**": "#### 📈 **The U-Shaped Curve**",
    "# Konseptuell illustrasjon av forholdet": "# Conceptual illustration of the relationship",
    "# Optimal batch størrelse er der generalisering er høyest": "# Optimal batch size is where generalization is highest",
    "# og overfitting-risiko er lavest": "# and overfitting risk is lowest",
    "#### 🔍 **Når Gjelder Hvilken Regel?**": "#### 🔍 **When Does Each Rule Apply?**",
    "##### **Større Batch for Bedre Generalisering:**": "##### **Larger Batch for Better Generalization:**",
    "- **Store, diverse datasett**": "- **Large, diverse datasets**",
    "- **Stabile, veldefinerte problemer**": "- **Stable, well-defined problems**",
    "- **Når du har nok data**": "- **When you have enough data**",
    "- **Produksjonsmodeller**": "- **Production models**",
    "##### **Mindre Batch for Overfitting-avverging:**": "##### **Smaller Batch for Overfitting Prevention:**",
    "- **Små datasett**": "- **Small datasets**",
    "- **Komplekse, støyete problemer**": "- **Complex, noisy problems**",
    "- **Når du har lite data**": "- **When you have little data**",
    "- **Forskningsmodeller**": "- **Research models**",
    "#### 🏥 **Medisinsk Eksempel: Hjerte-kar-sykdom**": "#### 🏥 **Medical Example: Cardiovascular Disease**",
    "##### **Scenario 1: Stor, representativ database**": "##### **Scenario 1: Large, representative database**",
    "# 100,000 pasienter, velbalansert": "# 100,000 patients, well-balanced",
    "# Anbefaling: Større batch (128-256)": "# Recommendation: Larger batch (128-256)",
    "# Grunn: Bedre generalisering, mindre støy": "# Reason: Better generalization, less noise",
    "##### **Scenario 2: Liten, sjeldne sykdommer**": "##### **Scenario 2: Small, rare diseases**",
    "# 1,000 pasienter, sjeldne tilfeller": "# 1,000 patients, rare cases",
    "# Anbefaling: Mindre batch (16-32)": "# Recommendation: Smaller batch (16-32)",
    "# Grunn: Unngå overtilpasning, utforsk sjeldne mønstre": "# Reason: Avoid overfitting, explore rare patterns",
    "#### 📊 **Praktisk Rådgivning**": "#### 📊 **Practical Advice**",
    "##### **Start med Medium Batch:**": "##### **Start with Medium Batch:**",
    "# Start med batch størrelse 32-64": "# Start with batch size 32-64",
    "# Monitorér både generalisering og overtilpasning": "# Monitor both generalization and overfitting",
    "# Tilpass basert på resultater": "# Adjust based on results",
    "##### **Indikatorer for Optimal Batch Størrelse:**": "##### **Indicators for Optimal Batch Size:**",
    "- **Høy test-accuracy** (god generalisering)": "- **High test accuracy** (good generalization)",
    "- **Lite gap mellom trening/test accuracy** (lav overfitting)": "- **Small gap between training/test accuracy** (low overfitting)",
    "- **Stabil loss-kurve** (god konvergens)": "- **Stable loss curve** (good convergence)",
    "#### 🎯 **Oppdatert Tabell**": "#### 🎯 **Updated Table**",
    "| Batch Størrelse | Generalisering | Overfitting-risiko | Anbefaling |": "| Batch Size | Generalization | Overfitting Risk | Recommendation |",
    "| **1-8** | Lav | Lav | Små datasett, sjeldne sykdommer |": "| **1-8** | Low | Low | Small datasets, rare diseases |",
    "| **32-64** | Høy | Medium | **Start her** |": "| **32-64** | High | Medium | **Start here** |",
    "| **128-256** | Høy | Medium | Store datasett, produksjon |": "| **128-256** | High | Medium | Large datasets, production |",
    "| **512+** | Medium | Høy | Veldig store datasett |": "| **512+** | Medium | High | Very large datasets |",
    "#### 📚 **Konklusjon**": "#### 📚 **Conclusion**",
    "Løsningen på denne tilsynelatende motstriden er:": "The solution to this apparent contradiction is:",
    "1. **Begge utsagnene er sanne** - men i forskjellige kontekster": "1. **Both statements are true** - but in different contexts",
    "2. **Generalisering og overfitting-avverging** er relaterte men forskjellige konsepter": "2. **Generalization and overfitting prevention** are related but different concepts",
    "3. **Optimal batch størrelse** balanserer begge faktorene": "3. **Optimal batch size** balances both factors",
    "4. **Kontekst er viktig** - datasett størrelse, problem-kompleksitet, osv.": "4. **Context is important** - dataset size, problem complexity, etc.",
    "**Praktisk råd:** Start med batch størrelse 32-64, og tilpass basert på hvordan modellen presterer på både trenings- og testdata. <br>": "**Practical advice:** Start with batch size 32-64, and adjust based on how the model performs on both training and test data. <br>",
    "Ofte setter ogs størreslen på **tilgjengelig GPU-minne** (e.g. VRAM: 8 GB, 16 GB, 32 GB) en beskrankning på batch-størrelse (e.g. batch-størrelser 2, 4, 8)": "Often the size of **available GPU memory** (e.g., VRAM: 8 GB, 16 GB, 32 GB) also sets a constraint on batch size (e.g., batch sizes 2, 4, 8)",
    "#### 🏥 **Medisinsk Eksempel: Hjerte-kar-sykdom Prediksjon**": "#### 🏥 **Medical Example: Cardiovascular Disease Prediction**",
    "# Praktisk eksempel med PyTorch": "# Practical example with PyTorch",
    "# Forskjellige batch størrelser": "# Different batch sizes",
    "# Opprett DataLoader med ønsket batch størrelse": "# Create DataLoader with desired batch size",
    "#### 📊 **Sammenligning av Batch Størrelser**": "#### 📊 **Comparison of Batch Sizes**",
    "| Batch Størrelse | Stabilitet | Hastighet | Minne | Generalisering |": "| Batch Size | Stability | Speed | Memory | Generalization |",
    "| **1 (SGD)** | Lav | Høy | Lav | Varierende |": "| **1 (SGD)** | Low | High | Low | Varying |",
    "| **32-64** | Medium | Høy | Medium | God |": "| **32-64** | Medium | High | Medium | Good |",
    "| **128-256** | Høy | Medium | Høy | God |": "| **128-256** | High | Medium | High | Good |",
    "| **Hele datasettet** | Høyest | Lav | Høyest | Best |": "| **Entire dataset** | Highest | Low | Highest | Best |",
    "#### 🎯 **Praktiske Anbefalinger for Medisinsk AI**": "#### 🎯 **Practical Recommendations for Medical AI**",
    "##### **Start med Mini-batch:**": "##### **Start with Mini-batch:**",
    "- **Batch størrelse**: 32-64": "- **Batch size**: 32-64",
    "- **Grunn**: Balanserer stabilitet og hastighet": "- **Reason**: Balances stability and speed",
    "- **Tilpas**: Øk hvis du har mye minne, mink hvis du har lite": "- **Adjust**: Increase if you have lots of memory, decrease if you have little",
    "##### **Tilpass til datasett:**": "##### **Adjust to dataset:**",
    "- **Store datasett**: Bruk større batch": "- **Large datasets**: Use larger batch",
    "- **Små datasett**: Bruk mindre batch": "- **Small datasets**: Use smaller batch",
    "- **Ubalanserte datasett**: Vurder weighted sampling": "- **Imbalanced datasets**: Consider weighted sampling",
    "##### **Monitorér trening:**": "##### **Monitor training:**",
    "- **Stabil loss**: Batch størrelsen fungerer": "- **Stable loss**: Batch size is working",
    "- **Oscillerende loss**: Prøv større batch": "- **Oscillating loss**: Try larger batch",
    "- **Treig trening**: Prøv mindre batch": "- **Slow training**: Try smaller batch",
    "#### 🔍 **Avanserte Teknikker**": "#### 🔍 **Advanced Techniques**",
    "##### **1. Gradient Accumulation**": "##### **1. Gradient Accumulation**",
    "# Simulerer større batch når du har lite minne": "# Simulates larger batch when you have little memory",
    "##### **2. Adaptive Batch Størrelse**": "##### **2. Adaptive Batch Size**",
    "# Øk batch størrelse når loss stabiliseres": "# Increase batch size when loss stabilizes",
    "**Batchvis oppdatering** påvirker både gradient nedstigning og backpropagation:": "**Batch update** affects both gradient descent and backpropagation:",
    "- **Backpropagation**: Beregner gradienter for hele batchen samtidig": "- **Backpropagation**: Calculates gradients for the entire batch simultaneously",
    "- **Gradient nedstigning**: Oppdaterer vekter basert på gjennomsnittlige gradienter": "- **Gradient descent**: Updates weights based on average gradients",
    "**Hovedfordeler:**": "**Main benefits:**",
    "- **Stabilitet**: Mer stabil læring": "- **Stability**: More stable learning",
    "- **Effektivitet**: Bedre utnyttelse av moderne hardware": "- **Efficiency**: Better utilization of modern hardware",
    "- **Generalisering**: Bedre generalisering til nye data": "- **Generalization**: Better generalization to new data",
    "**For medisinsk AI:**": "**For medical AI:**",
    "- Start med batch størrelse 32-64": "- Start with batch size 32-64",
    "- Tilpass basert på datasett og hardware (GPU VRAM)": "- Adjust based on dataset and hardware (GPU VRAM)",
    "- Monitorér trening for å finne optimal størrelse": "- Monitor training to find optimal size",
    "Dette er en av de viktigste hyperparametrene å tune når du trener nevrale nettverk for medisinske applikasjoner.": "This is one of the most important hyperparameters to tune when training neural networks for medical applications.",
}

def translate_cell(cell_content):
    result = cell_content
    for norwegian, english in translations.items():
        result = result.replace(norwegian, english)
    return result

for cell in notebook['cells']:
    if cell['cell_type'] == 'markdown':
        content = ''.join(cell['source'])
        translated = translate_cell(content)
        cell['source'] = [line + '\n' if i < len(translated.split('\n')) - 1 else line 
                         for i, line in enumerate(translated.split('\n'))]
    elif cell['cell_type'] == 'code':
        new_source = []
        for line in cell['source']:
            translated_line = translate_cell(line)
            new_source.append(translated_line)
        cell['source'] = new_source

with open('B2-learning-in-nn.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook, f, ensure_ascii=False, indent=2)

print("Translation part 5 complete!")

